loki:
  extraMemberlistConfig:
    bind_addr:
      - ${MY_POD_IP}

  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4

  commonConfig:
    ring:
      kvstore:
        store: memberlist

deploymentMode: SimpleScalable

backend:
  replicas: 2
  resources: {}
  persistence:
    volumeClaimsEnabled: false
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  extraArgs:
    - -config.expand-env=true

read:
  replicas: 2
  resources: {}
  persistence:
    volumeClaimsEnabled: false
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  extraArgs:
    - -config.expand-env=true

write:
  replicas: 3
  resources: {}
  persistence:
    volumeClaimsEnabled: false
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  extraArgs:
    - -config.expand-env=true

# Enable minio for storage
minio:
  enabled: true
  mode: standalone
  replicas: 1
  rootUser: admin
  rootPassword: adminpassword
  persistence:
    enabled: true
    size: 5Gi
    existingClaim: "minio-pvc"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

chunksCache:
  allocatedMemory: 128
  writebackSizeLimit: 25MB
  resources:
    requests:
      cpu: 40m
      memory: 128Mi
    limits:
      cpu: 80m
      memory: 128Mi

gateway:
  service:
    type: LoadBalancer


# Zero out replica counts of other deployment modes
singleBinary:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
test:
  enabled: false
lokiCanary:
  enabled: false
