
replicas: 1

image:
  registry: docker.io
  repository: grafana/grafana
  tag: ""

testFramework:
  enabled: false

ingress:
  enabled: true
  hosts:
    - grafana

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  type: pvc
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  existingClaim: grafana-441

adminUser: admin
adminPassword: admin


