# https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-collector/0.116.0
image:
  repository: "otel/opentelemetry-collector-k8s"
  tag: "0.119.0"

command:
  name: "otelcol-k8s"

mode: "daemonset"

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
  kubernetesEvents:
    enabled: true
#  kubernetesAttributes:
#    enabled: true
#    extractAllPodLabels: true
#    extractAllPodAnnotations: true

config:
  processors:
    attributes:
      actions:
        - key: environment
          value: production
          action: insert
    transform/logs:
      error_mode: ignore
      log_statements:
        - replace_pattern(log.body, "user_id=[^ ]+", "user_id=***")
  exporters:
    otlphttp:
      endpoint: "http://loki-gateway/otlp"
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
  service:
    pipelines:
      logs:
        exporters:
          - otlphttp
        processors:
          - memory_limiter
          - batch
          - attributes
          - transform/logs
      metrics: null
      traces: null

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi

