apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: grafana
  name: grafana-441
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeName: grafana-441