config:
  argocd:
    grpcWeb: false
    serverAddress: "http://argo-cd-argocd-server"
    insecure: true
    plaintext: true

  registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      #credentials: env:DOCKER_HUB_CREDS=username:passowrd

