apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-promethues
  name: grafana-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeName: grafana-pv