apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: promethues-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: promethues-pv
  storageClassName: monitoring-sc