apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-volume
spec:
  replicas: 1
  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: prometheus-volume
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce