apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prometheus
  name: prometheus
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeName: prometheus