server:

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteMany
    existingClaim: prometheus
    size: 1Gi

  replicaCount: 1

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  ## Prometheus data retention period (default if not specified is 15 days)
  ##
  retention: "30d"

  ## Prometheus' data retention size. Supported units: B, KB, MB, GB, TB, PB, EB.
  ##
  retentionSize: ""

kube-state-metrics:
  enabled: false

alertmanager:
  enabled: false